# Generated by Django 2.1.2 on 2019-11-19 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(default='First', max_length=20)),
                ('last', models.CharField(default='Last', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.CharField(blank=True, default='Forever a mystery', max_length=500)),
                ('approved', models.BooleanField(default=False)),
                ('user_type', models.CharField(default='user', max_length=10)),
                ('bio', models.TextField(default="User hasn't set a bio yet")),
                ('persons', models.ManyToManyField(to='profiles.PersonProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
