# Generated by Django 2.1.2 on 2019-11-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_me',
            field=models.CharField(default='Forever a mystery', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='persons',
            field=models.ManyToManyField(blank=True, to='profiles.PersonProfile'),
        ),
    ]
