# Generated by Django 2.1.2 on 2019-11-19 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('street_other', models.CharField(blank=True, max_length=255, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_creator', to='profiles.PersonProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CallReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(default='Call Report')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(default='no warning description description')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citation_creator', to='profiles.PersonProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CitationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Citation Type', max_length=100)),
                ('description', models.CharField(default='Citation Description', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Department Name', max_length=255)),
                ('short', models.CharField(blank=True, max_length=255, null=True)),
                ('max_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description', models.TextField(default='No department description')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(default='1A-25', max_length=50)),
                ('status', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Robbery', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MapCountyOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CountyOption', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MapStreetOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='StreetOption', max_length=255)),
                ('postal', models.CharField(blank=True, max_length=10, null=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='street_county', to='cad.MapCountyOption')),
            ],
        ),
        migrations.CreateModel(
            name='UnitStatusOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='10-8', max_length=20)),
                ('description', models.CharField(default='Available', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserVehicleMakeChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='vehicle make', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserVehicleModelChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='vehicle model', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(default='no warning description description')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warning_creator', to='profiles.PersonProfile')),
                ('department_issuing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wawrning_issuing_department', to='cad.Department')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warning_person', to='profiles.PersonProfile')),
            ],
        ),
        migrations.CreateModel(
            name='WarningType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Warning Type', max_length=100)),
                ('description', models.CharField(default='Warning Description', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(default='no warrant description')),
                ('call', models.ManyToManyField(to='cad.Call')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warrant_creator', to='profiles.PersonProfile')),
                ('department_issuing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warrant_issuing_department', to='cad.Department')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wanted_person', to='profiles.PersonProfile')),
            ],
        ),
        migrations.CreateModel(
            name='WarrantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Warrant Type', max_length=100)),
                ('description', models.CharField(default='Warrant Description', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='warrant',
            name='type',
            field=models.ManyToManyField(to='cad.WarrantType'),
        ),
        migrations.AddField(
            model_name='warning',
            name='type',
            field=models.ManyToManyField(to='cad.WarningType'),
        ),
        migrations.AddField(
            model_name='uservehicle',
            name='make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uservehicle_make', to='cad.UserVehicleMakeChoice'),
        ),
        migrations.AddField(
            model_name='uservehicle',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uservehicle_model', to='cad.UserVehicleModelChoice'),
        ),
        migrations.AddField(
            model_name='citation',
            name='department_issuing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citation_issuing_department', to='cad.Department'),
        ),
        migrations.AddField(
            model_name='citation',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citation_person', to='profiles.PersonProfile'),
        ),
        migrations.AddField(
            model_name='citation',
            name='type',
            field=models.ManyToManyField(to='cad.CitationType'),
        ),
        migrations.AddField(
            model_name='call',
            name='departments',
            field=models.ManyToManyField(to='cad.Department'),
        ),
        migrations.AddField(
            model_name='call',
            name='incident_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CALL_INCIDENT', to='cad.IncidentType'),
        ),
        migrations.AddField(
            model_name='call',
            name='reports',
            field=models.ManyToManyField(to='cad.CallReport'),
        ),
        migrations.AddField(
            model_name='call',
            name='street1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MAP_STREET_1', to='cad.MapStreetOption'),
        ),
        migrations.AddField(
            model_name='call',
            name='street2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MAP_STREET_2', to='cad.MapStreetOption'),
        ),
        migrations.AddField(
            model_name='call',
            name='units',
            field=models.ManyToManyField(to='cad.DepartmentUnit'),
        ),
    ]
